version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["bootstrap 4"]

[[transformers]]
name = "php-cs-fixer"